pushing 90 % complete sign up flow for review
agordon123/git_note pull request #10
Opened 2024-03-06 14:45 UTC by agordon123

I dropped comments under all the parts that are confusing me.  the server actions ive made may or may not work (in one case I dont think it will work but it depends on the answer to so many other questions i have that i couldn't exactly

2024-03-06 22:07 UTC, brandonetter requested changes
I know it isn't part of this branch, but the giant string of errors from the 'buttonType' is killing me :)

Let's address that.

```js
// components/shared/CustomButton.tsx

...
const CustomButton = React.forwardRef<HTMLButtonElement, CustomButtonProps>(
  ({ ...props }, ref) => {
    const { buttonType, className, children } = props;
    
```

Change this to use `rest params` to pull everything else except what we named out of props:
```js
    const { buttonType, className, children, ...rest } = props;
```

Then, instead of returning the Button with 'props' spread in- let's return the button with the 'rest' we pulled out of props:

```js
  return (
      <Button
        ref={ref}
        className={`${button.className} ${className}`}
        {...rest} <--- here
      >
        {button.icon && <Image src={button.icon} alt={buttonType} />}
        {children}
      </Button>
    );
 ```


Good start so far.


After you fix these other changes you'll need to go into `user.actions.ts` and modify what you send. You aren't able to create users because our database REQUIRES an image

![image](https://github.com/agordon123/git_note/assets/4108484/b884039a-57cc-46a3-b3cd-329074211b3e)

Either change the requirement or provide one to the User.create (you should await the userCreate as well if you want to return it)

![image](https://github.com/agordon123/git_note/assets/4108484/bf1db0a5-4952-4bea-a066-05e351a1bc2c)


With all of these changes i was able to register with credentials and then login :)

2024-03-06 22:07 UTC, brandonetter commented on components/auth/SignUpForm.tsx
This signUp form says "Login"

2024-03-06 22:07 UTC, brandonetter commented on components/auth/SignUpForm.tsx
> +      setDisabled(false);
Instead of creating a setDisabled state, let's use a transition! Transitions are meant EXACTLY for this kind of thing.

Import `useTransition` from react at the top. Then replace our 'disabled' use state with this:

![image](https://github.com/agordon123/git_note/assets/4108484/6d8544a9-9b14-4a28-afda-1197d0367d06)

Then we wrap our code with "startTransition"



https://github.com/agordon123/git_note/assets/4108484/2eafd0dc-2eee-44a4-a456-b7a85d15e174

2024-03-06 22:07 UTC, brandonetter commented on app/api/auth/register/route.ts
There's already a catchall route here ([...nextauth]).
Move this folder and file `register/route.ts` out of this folder.

Try

`api/register/route.ts` instead. This code doesn't ever run.

2024-03-06 22:07 UTC, brandonetter commented on lib/authOptions.ts
>          if (credentials?.password! || credentials?.username! === null)
```suggestion
        if (credentials?.password === null || credentials?.username! === null)
```

The "!" at the end of the variable doesn't make it a negative. That just asserts that is exists. You essentially had "if there's a password, throw an error"

2024-03-06 22:07 UTC, brandonetter commented on lib/authOptions.ts
> +          if (!user) {
```suggestion
          if (user) {
```
This is backwards. You're trying to validate the password if you DON'T have a user. You should do one step at a time and test your code multiple times. These kind of errors should be caught in testing.

2024-03-06 22:16 UTC, agordon123 commented on components/auth/SignUpForm.tsx
ah yea i saw that and meant to change it, woops.

2024-03-06 22:17 UTC, agordon123 commented on components/auth/SignUpForm.tsx
> +      setDisabled(false);
have not used that hook before, good information

2024-03-07 15:54 UTC, brandonetter commented
@agordon123 One last thing. We have a bug where we try to login the user after registering. But we don't double check that the user hasn't already been created when they try to register.

This video explains the first section of the fix- but it'll be up to you to implement the rest :) I trust you.

https://github.com/agordon123/git_note/assets/4108484/3d7b6691-9c13-40da-8934-dbe4691bb927

2024-03-07 17:36 UTC, brandonetter approved these changes
Changes made in meeting. All set now :)

2024-03-07 17:37 UTC, merged